In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [4]:
X_test_full = pd.read_csv('test.csv')

In [5]:
X_test_full

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1700,1,1.9,0,0,1,54,0.5,170,...,17,644,913,2121,14,8,15,1,1,0
996,997,609,0,1.8,1,0,0,13,0.9,186,...,2,1152,1632,1933,8,1,19,0,1,1
997,998,1185,0,1.4,0,1,1,8,0.5,80,...,12,477,825,1223,5,0,14,1,0,0
998,999,1533,1,0.5,1,0,0,50,0.4,171,...,12,38,832,2509,15,11,6,0,1,0
999,1000,1270,1,0.5,0,4,1,35,0.1,140,...,19,457,608,2828,9,2,3,1,0,1

In [6]:
df = df.drop_duplicates()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 343.8 KB

In [8]:
df.price_range.value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [9]:
X_test_full = X_test_full.drop_duplicates()

In [10]:
X_test_full.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 171.9 KB

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
X = sc.fit_transform(X)

In [16]:
X

array([[-0.90259726, -0.9900495 ,  0.83077942, ..., -1.78686097,
        -1.00601811,  0.98609664],
       [-0.49513857,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       [-1.5376865 ,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       ...,
       [ 1.53077336, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789, -1.01409939],
       [ 0.62252745, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789,  0.98609664],
       [-1.65833069,  1.0100505 ,  0.58562134, ...,  0.55964063,
         0.99401789,  0.98609664]])

In [17]:
X_test = sc.fit_transform(X_test_full)

In [18]:
X_test

array([[-1.73031962, -0.47545131,  0.968496  , ..., -1.76021608,
         1.        , -1.01409939],
       [-1.72685552, -0.94278218,  0.968496  , ...,  0.56811207,
        -1.        , -1.01409939],
       [-1.72339142,  1.29207729,  0.968496  , ..., -1.76021608,
         1.        ,  0.98609664],
       ...,
       [ 1.72339142, -0.1469316 , -1.03252879, ...,  0.56811207,
        -1.        , -1.01409939],
       [ 1.72685552,  0.65817305,  0.968496  , ..., -1.76021608,
         1.        , -1.01409939],
       [ 1.73031962,  0.04971753,  0.968496  , ...,  0.56811207,
        -1.        ,  0.98609664]])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [20]:
from xgboost import XGBClassifier , XGBRFClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report as cr , confusion_matrix as cm , accuracy_score as ac

In [21]:
logreg_without_overfitting = LogisticRegression(C = 0.01)
logreg_with_overfitting = LogisticRegression()
dtree = DecisionTreeClassifier()
rf = RandomForestClassifier(n_estimators=500)
xgc = XGBClassifier()
xgbRFc = XGBRFClassifier()

In [22]:
def model(model):
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    print(cr(y_test,ypred))
    print("Accuracy Score is :",ac(y_test,ypred)*100)

In [23]:
model(dtree)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90       169
           1       0.78      0.78      0.78       162
           2       0.73      0.75      0.74       162
           3       0.85      0.84      0.85       167

    accuracy                           0.82       660
   macro avg       0.82      0.82      0.82       660
weighted avg       0.82      0.82      0.82       660

Accuracy Score is : 81.81818181818183

In [24]:
model(rf)

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       169
           1       0.83      0.86      0.84       162
           2       0.82      0.81      0.81       162
           3       0.93      0.91      0.92       167

    accuracy                           0.88       660
   macro avg       0.88      0.88      0.88       660
weighted avg       0.88      0.88      0.88       660

Accuracy Score is : 88.03030303030303

In [25]:
model(logreg_with_overfitting)

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       169
           1       0.92      0.97      0.94       162
           2       0.97      0.92      0.95       162
           3       0.96      0.99      0.98       167

    accuracy                           0.96       660
   macro avg       0.96      0.96      0.96       660
weighted avg       0.96      0.96      0.96       660

Accuracy Score is : 95.9090909090909

In [26]:
model(logreg_without_overfitting)

              precision    recall  f1-score   support

           0       0.82      0.98      0.89       169
           1       0.76      0.60      0.67       162
           2       0.76      0.64      0.69       162
           3       0.83      0.97      0.90       167

    accuracy                           0.80       660
   macro avg       0.79      0.80      0.79       660
weighted avg       0.79      0.80      0.79       660

Accuracy Score is : 79.84848484848484

In [27]:
model(xgc)

[18:05:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       169
           1       0.88      0.91      0.89       162
           2       0.86      0.85      0.86       162
           3       0.93      0.92      0.93       167

    accuracy                           0.91       660
   macro avg       0.91      0.91      0.91       660
weighted avg       0.91      0.91      0.91       660

Accuracy Score is : 91.06060606060606

In [28]:
model(xgbRFc)

[18:05:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       169
           1       0.81      0.86      0.84       162
           2       0.80      0.80      0.80       162
           3       0.93      0.89      0.91       167

    accuracy                           0.87       660
   macro avg       0.87      0.87      0.87       660
weighted avg       0.87      0.87      0.87       660

Accuracy Score is : 86.96969696969697